services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@91.98.85.187:5432/nodes-db
      PORT: 3000
      NODE_ENV: production
      UV_THREADPOOL_SIZE: 64

  pgadmin:
    image: sosedoff/pgweb:latest
    restart: unless-stopped
    ports:
      - "5050:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://myuser:mypassword@91.98.85.187:5432/nodes-db?sslmode=disable
